name: Deploy Azure Function App - UploadSupplyChainAudioTranscriptions
 
on:
  push:
    branches:
      - master
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
 
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
 
      - name: Install Azure Functions Core Tools
        run: |
          npm install -g azure-functions-core-tools@4 --unsafe-perm true
 
      - name: Login to Azure
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
 
      - name: Publish to Azure Function App
        run: |
          cd UploadSupplyChainAudioTranscriptions
          func azure functionapp publish UploadSupplyChainAudioTranscriptions --dotnet-isolated